### ISSUE TITLE
Strapi 5

### ISSUE THREAD

**Issue by yevhenskakun** [pluginpal/strapi-plugin-publisher#141]
Do you plan to support strapi v5?

**Comment by TMSchipper** [comment]
@yevhenskakun, we have taken over the maintainership of this project and will proceed with the update to version 5 as soon as possible. 

Kind regards, 
PluginPal

**Comment by boazpoolman** [comment]
test

**Comment by LinkX-shomasakamoto** [comment]
Hi @TMSchipper ,
I’ve been using the amazing Publisher plugin with Strapi v4, and I deeply appreciate the efforts of your development team!

Could you kindly share if there’s an expected migration date for Strapi v5? I’m eagerly looking forward to the new features and improvements in the upcoming version.

Thank you again for your fantastic work, and I look forward to supporting this great project further!

**Comment by TMSchipper** [comment]
Hi @LinkX-shomasakamoto, thank you for your support! We will start coming week with the Strapi V5 update

**Comment by hevar** [comment]
Keep up the good work, looking forward to an update!

**Comment by svoelz** [comment]
Hi, we love this plugin. Is there an estimation when the strapi 5 version will be available?

**Comment by TMSchipper** [comment]
Hi everyone,
We decided to take a break for Christmas. Coincidentally, I am working on the update to V5 again today. It is quite a big job since the V5 update of Strapi affects a lot of the publisher plugin.
Thanks for your patience!

I hope to be able to roll out a beta at the end of this month!

**Comment by maruthasalamr** [comment]
Do you have any update on strapi v5 compatibility ?

**Comment by boazpoolman** [comment]
Hi all!

We are working very hard to finish the migration ASAP.
Mostly @TMSchipper has been working many evenings to make this happen.

The time put in to this project is all contributed on the side, in our free time. That is why we can not give an accurate estimate as to when the migration will be finished. Our priorities might shift causing us to focus on other projects.

That being said, if you are willing to sponsor the Publisher Plugin we can schedule dedicated development time and offer a clear timeline for the work. If you're interested in this, please contact us on [info@pluginpal.io](mailto:info@pluginpal.io)

**Comment by TMSchipper** [comment]
@khanhhood and others, we're ready for a beta release! The plan is to launch it this coming Wednesday.

**Comment by khanhhood** [comment]
> [@khanhhood](https://github.com/khanhhood) and others, We’ve just tested and added the final commits. We’re now ready for the beta release! The plan is to launch it this coming Wednesday. 🚀

Thank you so much @TMSchipper . I'm so excited to wait for this plugins

**Comment by TMSchipper** [comment]
Hi everyone,

Today, we released the beta version of the Strapi Publisher Plugin:
🔗 [strapi-plugin-publisher@2.0.0-beta.1](https://www.npmjs.com/package/strapi-plugin-publisher/v/2.0.0-beta.1)

Installation
**Yarn:**
`yarn add strapi-plugin-publisher@beta`

**NPM:**
`npm i strapi-plugin-publisher@beta`

Apologies if this took a bit longer than expected. Hopefully, this beta release provides what you need! If you have any questions or run into any issues, please let me know.

If everything runs smoothly and no major issues are reported within the next two weeks, we’ll publish a stable version so you won’t need to install it under the beta tag anymore.

Thanks for your support and patience!

Kind regards,
Tim Schipper
PluginPal

**Comment by maruthasalamr** [comment]
thank you so much @TMSchipper

**Comment by maruthasalamr** [comment]
Node Version
v18.20.2

NPM/Yarn/PNPM Version
10.5.0

Strapi Version
5.5.1

Operating System
MacOS

Database
PostgreSQL

Javascript or Typescript
Javascript

strapi-plugin-publisher - 2.0.0-beta.1

Got issue while installed above beta version when i try to open any document strapi

<img width="1316" alt="Image" src="https://github.com/user-attachments/assets/f16ade5c-b2e9-4aa7-ac59-9b685b51d4b3" />

@TMSchipper

**Comment by TMSchipper** [comment]
@maruthasalamr thank you for reporting your issue. I was able to reproduce your issue with the following steps:

1. Create a strapi project.
2. Install the beta version of the publisher with `yarn add strapi-plugin-publisher@beta`
3. Run `yarn run start`.

Did you also run `yarn run build`?
If not, could you try running `yarn run build` and when this is completed run `yarn run start` or `yarn run develop`

Let me know if this helps!

**Comment by douwepausma** [comment]
Thanks @TMSchipper !  Looking forward to trying it out, I however encountered an issue with the latest Strapi version. I ran into a dependency conflict. Updating `react-router-dom` to `6.0.0` should probably resolve it.

```
npm error peer react-router-dom@"^6.0.0" from @strapi/strapi@5.10.3
npm error node_modules/@strapi/strapi
```

**Comment by boazpoolman** [comment]
Hi @douwepausma,

This issue should now be resolved with the latests beta `v2.0.0-beta.2`.

**Comment by maruthasalamr** [comment]
@TMSchipper yes
1.Installed the beta version yarn add strapi-plugin-publisher@beta
2.yarn run build
3. yarn develop

I'm getting the error

**Comment by khanhhood** [comment]
HI @TMSchipper 
I did with your guide : 

1. Installed the beta version yarn add strapi-plugin-publisher@beta
2. Update config/plugins 
'publisher': {
    enabled: true,
  },
3.yarn run build
4. yarn develop

But cannot see the publisher section on the content editing page 

Note: I worked well on my Strapi 4, But after migrating to Strapi 5.  It doesn't work 

What is wrong with my steps?

**Comment by TMSchipper** [comment]
@khanhhood I'm also encountering these issues now, unfortunately. I'll investigate as soon as possible and keep you all updated. I think it has something to do with the dependencies that are updated.

**Comment by khanhhood** [comment]
> [@khanhhood](https://github.com/khanhhood) I'm also encountering these issues now, unfortunately. I'll investigate as soon as possible and keep you all updated. I think it has something to do with the dependencies that are updated.

Many Thanks  @TMSchipper 

It's my dependencies on my packages.json

"dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^5.0.1",
    "@strapi/plugin-documentation": "5.10.2",
    "@strapi/plugin-users-permissions": "5.10.2",
    "@strapi/provider-upload-aws-s3": "5.10.2",
    "@strapi/strapi": "5.10.2",
    "knex": "^1.0.5",
    "patch-package": "^6.4.7",
    "pg": "^8.7.3",
    "postmark": "^2.7.8",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "slugify": "^1.6.5",
    "strapi-plugin-meilisearch": "^0.13.1",
    "strapi-plugin-preview-button": "^3.0.0",
    "strapi-plugin-publisher": "^2.0.0-beta.2",
    "strapi-provider-upload-imagekit": "^4.15.0",
    "styled-components": "^6.0.0",
    "vimeo": "^2.1.1",
    "web-push": "^3.5.0",
    "yarn": "^1.22.22"
  },

**Comment by boazpoolman** [comment]
Hi @khanhhood,

This issue should now be fixed with the latest beta `v2.0.0-beta.3`.
Please let us know if this version is working for you!

**Comment by khanhhood** [comment]
> Hi [@khanhhood](https://github.com/khanhhood),
> 
> This issue should now be fixed with the latest beta `v2.0.0-beta.3`. Please let us know if this version is working for you!

worked well  @TMSchipper . Thank you so much. I will have a deep test later 

<img width="1403" alt="Image" src="https://github.com/user-attachments/assets/200f8e3c-b1f6-4af5-bcdb-d2988d505a48" />

**Comment by maruthasalamr** [comment]
working for me as well @TMSchipper. Thank you so much.

<img width="1382" alt="Image" src="https://github.com/user-attachments/assets/1f06a4c2-68b1-4b18-ba56-f1886375df6b" />

**Comment by boazpoolman** [comment]
A new beta was published `2.0.0-beta.4` fixing two bugs:

1. Slow response of the time input field
2. Issue in fetching the publication state before (de)publishing

**Comment by matumartin14** [comment]
I am using the latest beta version, but for me, the publisher section is still not visible.

**Comment by TMSchipper** [comment]
@matumartin14 can you give some more details? Are you using yarn or npm? Can you show me your dependencies in your package.json? If you are going to provide me this information, could you open a new issue?

FYI: I've created a fix for documents that are "modified" aren't publishing. This fix will be included in the upcoming beta.

**Comment by matumartin14** [comment]
> [@matumartin14](https://github.com/matumartin14) can you give some more details? Are you using yarn or npm? Can you show me your dependencies in your package.json? If you are going to provide me this information, could you open a new issue?
> 
> FYI: I've created a fix for documents that are "modified" aren't publishing. This fix will be included in the upcoming beta.

https://github.com/pluginpal/strapi-plugin-publisher/issues/158

**Comment by TMSchipper** [comment]
A new beta was published `2.0.0-beta.5` fixing two bugs:

1. Fix plugin.ts config
2. Fix publish action when a document is 'modified'

**Comment by zul18** [comment]
Hi @TMSchipper , I have a issue, after creating entry. then this error appears.

![Image](https://github.com/user-attachments/assets/69d8561b-799b-4dfe-8f09-2c4e8b827f75)

![Image](https://github.com/user-attachments/assets/62c9c5e4-54b6-4038-8d73-97ff3a4868ee)

**Comment by TMSchipper** [comment]
@zul18 thanks for reaching out! At the moment, I’m unable to reproduce it on my end, so I’ll need more details to investigate further. Could you create a new issue?

**Comment by wujiesixing** [comment]
After configuring internationalization, publish and unpublish no longer work.

**Comment by TMSchipper** [comment]
@wujiesixing, thanks for reaching out.

But can you explain your issue a bit more or even better create a new issue.

**Comment by TMSchipper** [comment]
Hi all,

I've just released a new version: https://www.npmjs.com/package/strapi-plugin-publisher/v/2.0.0-beta.7

Fix:
-Validation issues
-Translation issues

**Comment by freshsid** [comment]
> After configuring internationalization, publish and unpublish no longer work.

Same here

**Comment by TMSchipper** [comment]
Thanks for reporting, I'll investage this bug tonight. For now I've created a new [issue](https://github.com/pluginpal/strapi-plugin-publisher/issues/172) so you can follow new information or a status update.

**Comment by amhouel** [comment]
I can't save the publishing date when the entity has required images - I get a validation error `Warning: 2 errors occurred` even when the 2 required images have been uploaded and the entity has been saved. Publishing with the strapi publish button works as expected. I'm using Strapi 5 with strapi-plugin-publisher@2.0.0-beta.10.

**Comment by boazpoolman** [comment]
Hi @amhouel,

I just did a quick test and was not able to reproduce this based of your comment.

Could you write up a new issue, adhering to the bug template? Hopefully we can then reproduce and solve this issue!

**Comment by boazpoolman** [comment]
The stable version for v5 is here!

Thank you everybody for testing our beta throughout the last couple months.
 
You can now install [version v2.0.0](https://github.com/pluginpal/strapi-plugin-publisher/releases/tag/2.0.0).
